name: Build Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements-macos.txt

      - name: Build macOS app
        run: python build.py --platform macos

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: Dota2本色风情-macOS
          path: Dota2本色风情.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements-windows.txt

      - name: Build Windows exe
        run: python build.py --platform windows

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: Dota2本色风情-Windows
          path: dist/Dota2本色风情.exe
